name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install --no-root
    - name: Cache build venv
      uses: actions/cache@v3
      with:
        path: /home/runner/work/<path>/example-app/.venv
        key: ${{ runner.os }}-venv
    concurrency:
      group: dependency-installation

  static-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      # Steps for linter, formatter, security checks
    concurrency:
      group: static-tests

  unit-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      # Steps for unit tests
    concurrency:
      group: unit-tests
